### ISSUE TITLE
Update to com.android.tools.build:gradle-experimental:0.7.0-beta3

### ISSUE THREAD

**Issue by winterDroid** [crystax/android-samples-android-studio#1]
Since the dependency management got much simpler with the latest versions of the experimental plugin, probably integration is now better. Could you please upgrade the example?

**Comment by dmsck** [comment]
Sure, this is in progress. Will be done soon.

**Comment by dmsck** [comment]
[Done](https://github.com/crystax/android-samples-android-studio/commit/c79b498892c05804ca77a2cc0ff5d70f9f8f5d11)
